postfix_mail_admin/models/domain.py
from ..services import db
from .base import BaseModel


class Domain(BaseModel):
    """The mail domain"""

    __tablename__ = "domains"

    fqdn = db.Column(
        db.String(150),
        unique=True,
        nullable=False,
        info={"label": "Domain name"},
    )

    mailboxes = db.relationship(
        "Mailbox", lazy=True, backref=db.backref("domain", lazy=False)
    )
    aliases = db.relationship(
        "Alias", lazy=True, backref=db.backref("domain", lazy=False)
    )

    def __str__(self):
        return self.fqdn

    def __repr__(self):
        return f"<Domain {self.fqdn}>"

    def __hash__(self):
        return hash((self.id, self.fqdn,))

postfix_mail_admin/views/domains.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required

from ..forms import DomainForm
from ..services import db
from ..models import Domain

domains_blueprint = Blueprint("domains", __name__)


@domains_blueprint.route("/", endpoint="index")
@login_required
def index():
    domains = Domain.query.all()
    return render_template("domains/index.html", domains=domains)


@domains_blueprint.route("/create", endpoint="create", methods=["GET", "POST"])
@login_required
def create():
    form = DomainForm()

    if form.validate_on_submit():
        domain = Domain()
        form.populate_obj(domain)

        db.session.add(domain)
        db.session.commit()

        flash(f"Domain {domain.fqdn} has been successfully created", "success")
        return redirect(url_for(".index"))

    return render_template("domains/create.html", form=form)


@domains_blueprint.route(
    "/<int:domain_id>/edit", endpoint="edit", methods=["GET", "POST"]
)
@login_required
def edit(domain_id):
    domain: Domain = Domain.query.get_or_404(domain_id)
    form = DomainForm(obj=domain)

    if form.validate_on_submit():
        form.populate_obj(domain)

        db.session.add(domain)
        db.session.commit()

        flash(f"Domain {domain.fqdn} has been successfully updated", "success")
        return redirect(url_for(".index"))

    return render_template("domains/edit.html", domain=domain, form=form)


@domains_blueprint.route("/<int:domain_id>/delete", endpoint="delete")
@login_required
def remove(domain_id):
    domain = Domain.query.get_or_404(domain_id)
    db.session.delete(domain)
    db.session.commit()

    flash(f"Domain {domain.fqdn} has been successfully deleted", "success")
    return redirect(url_for(".index"))

postfix_mail_admin/templates/domains/_form.html
{{ form.hidden_tag() }}

<div class="form-group">
  {{ form.fqdn.label(class_="bmd-label-floating") }}
  {{ form.fqdn(class_="form-control is-invalid" if form.fqdn.errors else "form-control") }}
  {% if form.fqdn.errors %}
    <div class="invalid-feedback">
      {% for error in form.fqdn.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
  {% endif %}
</div>

<div class="mt-4 checkbox">
  <label for="{{ form.is_active.label.field_id }}">
    {{ form.is_active }}
    {{ form.is_active.label.text }}
  </label>
</div>

postfix_mail_admin/templates/domains/create.html
{% extends "base.html" %}

{% block title %}New domain{% endblock %}

{% block content %}
  <div class="mt-6 row justify-content-center">
    <div class="col-sm-12 col-md-6">
      <h1>Add a new domain</h1>

      <div class="mt-4">
        <form action="{{ url_for("domains.create") }}" method="post">
          {% include "domains/_form.html" %}

          <div class="mt-4 btn-group">
            <button type="submit" class="btn btn-raised btn-primary">Create</button>
            <a href="{{ url_for("domains.index") }}" class="ml-2 btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

postfix_mail_admin/templates/domains/edit.html
{% extends "base.html" %}

{% block title %}Edit {{ domain.fqdn }}{% endblock %}

{% block content %}
  <div class="mt-6 row justify-content-center">
    <div class="col-sm-12 col-md-6">
      <h1>Edit <code>{{ domain.fqdn }}</code></h1>

      <div class="mt-4">
        <form action="{{ url_for("domains.edit", domain_id=domain.id) }}" method="post">
          {% include "domains/_form.html" %}

          <div class="mt-4 btn-group">
            <button type="submit" class="btn btn-raised btn-primary">Save</button>
            <a href="{{ url_for("domains.index") }}" class="ml-2 btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

postfix_mail_admin/templates/domains/index.html
{% extends "base.html" %}

{% block title %}Domains{% endblock %}

{% block content %}
  <div class="mt-4">
    <div class="d-flex">
      <h1>Domains</h1>
      <div class="ml-auto">
        <a href="{{ url_for("domains.create") }}"
           class="btn btn-raised btn-primary d-inline-flex align-items-center"
          title="Add a new domain">
          <i class="material-icons">add</i>
          <span class="pl-1">Add</span>
        </a>
      </div>
    </div>

    <div class="mt-4 table-responsive-md">
      <table class="table table-sm">
        <thead>
          <tr>
            <th>ID</th>
            <th>Domain</th>
            <th>Is active?</th>
            <th>Created At</th>
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody>
          {% for domain in domains %}
            <tr>
              <th scope="row" class="align-middle">{{ domain.id }}</th>
              <td class="align-middle">{{ domain.fqdn }}</td>
              <td class="align-middle">
                {% if domain.is_active %}
                  <span class="text-success">
                    <i class="material-icons font-weight-bold">check</i>
                  </span>
                {% else %}
                  <span class="text-warning">
                    <i class="material-icons font-weight-bold">remove</i>
                  </span>
                {% endif %}
              </td>
              <td class="align-middle">{{ domain.created_at.strftime("%c") }}</td>
              <td class="align-middle">
                <div class="btn-toolbar btn-group-sm" role="toolbar" aria-label="Actions">
                  <a href="{{ url_for("domains.edit", domain_id=domain.id) }}"
                     class="btn btn-info" title="Edit">
                    <i class="material-icons">edit</i>
                  </a>
                  <a href="{{ url_for("domains.delete", domain_id=domain.id) }}"
                     class="btn btn-danger" title="Delete"
                     onclick="return confirm('Are you sure you want to delete {{ domain.fqdn }}?')"
                  >
                    <i class="material-icons">delete</i>
                  </a>
                </div>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}