postfix_mail_admin/views/aliases.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required
from flask_sqlalchemy import Pagination

from ..forms import AliasForm
from ..services import db
from ..models import Alias

aliases_blueprint = Blueprint("aliases", __name__)


@aliases_blueprint.route("/", endpoint="index")
@login_required
def index():
    pager: Pagination = Alias.query.paginate(per_page=25, max_per_page=50)
    return render_template("aliases/index.html", pager=pager)


@aliases_blueprint.route("/create", endpoint="create", methods=["GET", "POST"])
@login_required
def create():
    form = AliasForm()

    if form.validate_on_submit():
        alias = Alias()
        form.populate_obj(alias)

        db.session.add(alias)
        db.session.commit()

        flash(f"Alias {alias} has been successfully created", "success")
        return redirect(url_for(".index"))

    return render_template("aliases/create.html", form=form)


@aliases_blueprint.route(
    "/<int:alias_id>/edit", endpoint="edit", methods=["GET", "POST"]
)
@login_required
def edit(alias_id):
    alias = Alias.query.get_or_404(alias_id)
    form = AliasForm(obj=alias)

    if form.validate_on_submit():
        form.populate_obj(alias)

        db.session.add(alias)
        db.session.commit()

        flash(f"Alias {alias} has been successfully updated", "success")
        return redirect(url_for(".index"))

    return render_template("aliases/edit.html", alias=alias, form=form)


@aliases_blueprint.route("/<int:alias_id>/delete", endpoint="delete")
@login_required
def remove(alias_id):
    alias = Alias.query.get_or_404(alias_id)

    db.session.delete(alias)
    db.session.commit()

    flash(f"Alias {alias} has been successfully deleted", "success")
    return redirect(url_for(".index"))

postfix_mail_admin/templates/aliases/_form.html
{{ form.hidden_tag() }}

<div class="mt-4 form-row">
  <div class="col">
    <div class="form-group">
      {{ form.source.label(class_="bmd-label-static") }}
      {{ form.source(class_="form-control is-invalid" if form.source.errors else "form-control", autocomplete="off") }}
      {% if form.source.errors %}
        <div class="invalid-feedback">
          {% for error in form.source.errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </div>
  <div class="col">
    <div class="form-group">
      {{ form.domain.label(class_="bmd-label-static") }}
      <div class="input-group align-items-center">
        <div class="input-group-prepend mr-1">
          <span>&commat;</span>
        </div>
        {{ form.domain(class_="form-control is-invalid" if form.domain.errors else "form-control", size=1) }}
        {% if form.domain.errors %}
          <div class="invalid-feedback">
            {% for error in form.domain.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<div class="form-group">
  {{ form.destination.label(class_="bmd-label-static") }}
  {{ form.destination(class_="form-control is-invalid" if form.destination.errors else "form-control", autocomplete="off") }}
  {% if form.destination.errors %}
    <div class="invalid-feedback">
      {% for error in form.destination.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
  {% endif %}
</div>

<div class="mt-4 checkbox">
  <label for="{{ form.is_active.label.field_id }}">
    {{ form.is_active }}
    {{ form.is_active.label.text }}
  </label>
</div>

postfix_mail_admin/templates/aliases/create.html
{% extends "base.html" %}

{% block title %}New alias{% endblock %}

{% block content %}
  <div class="mt-6 row justify-content-center">
    <div class="col-sm-12 col-md-8">
      <h1>Add a new alias</h1>

      <div class="mt-4">
        <form action="{{ url_for("aliases.create") }}" method="post">
          {% include "aliases/_form.html" %}

          <div class="mt-4 btn-group">
            <button type="submit" class="btn btn-raised btn-primary">Create</button>
            <a href="{{ url_for("aliases.index") }}" class="ml-2 btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

postfix_mail_admin/templates/aliases/edit.html
{% extends "base.html" %}

{% block title %}Edit {{ alias }}{% endblock %}

{% block content %}
  <div class="mt-6 row justify-content-center">
    <div class="col-sm-12 col-md-8">
      <h2>Edit <code>{{ alias }}</code></h2>

      <div class="mt-4">
        <form action="{{ url_for("aliases.edit", alias_id=alias.id) }}" method="post">
          {% include "aliases/_form.html" %}

          <div class="mt-4 btn-group">
            <button type="submit" class="btn btn-raised btn-primary">Save</button>
            <a href="{{ url_for("aliases.index") }}" class="ml-2 btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

postfix_mail_admin/templates/aliases/index.html
{% extends "base.html" %}

{% block title %}Aliases{% endblock %}

{% block content %}
  <div class="mt-4">
    <div class="d-flex">
      <h1>Aliases</h1>
      <div class="ml-auto">
        <a href="{{ url_for("aliases.create") }}"
           class="btn btn-raised btn-primary d-inline-flex align-items-center"
           title="Add a new alias">
          <i class="material-icons">add</i>
          <span class="pl-1">Add</span>
        </a>
      </div>
    </div>

    <div class="mt-4 table-responsive-md">
      <table class="table table-sm">
        <thead>
        <tr>
          <th>ID</th>
          <th>Source</th>
          <th>Domain</th>
          <th>Destination</th>
          <th>Is active?</th>
          <th>Created At</th>
          <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        {% for alias in pager.items %}
          <tr>
            <th scope="row" class="align-middle">{{ alias.id }}</th>
            <td class="align-middle">{{ alias.source }}</td>
            <td class="align-middle">{{ alias.domain.fqdn }}</td>
            <td class="align-middle">{{ alias.destination }}</td>
            <td class="align-middle">
              {% if alias.is_active %}
                <span class="text-success">
                    <i class="material-icons font-weight-bold">check</i>
                  </span>
              {% else %}
                <span class="text-warning">
                    <i class="material-icons font-weight-bold">remove</i>
                  </span>
              {% endif %}
            </td>
            <td class="align-middle">{{ alias.created_at.strftime("%c") }}</td>
            <td class="align-middle">
              <div class="btn-toolbar btn-group-sm" role="toolbar" aria-label="Actions">
                <a href="{{ url_for("aliases.edit", alias_id=alias.id) }}"
                   class="btn btn-info" title="Edit">
                  <i class="material-icons">edit</i>
                </a>
                <a href="{{ url_for("aliases.delete", alias_id=alias.id) }}"
                   class="btn btn-danger" title="Delete"
                   onclick="return confirm('Are you sure you want to delete {{ alias.email }}?')"
                >
                  <i class="material-icons">delete</i>
                </a>
              </div>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

      <!-- Pagination -->
      {% from "helpers/_pagination.html" import render_pagination %}
      {{ render_pagination(pager, "aliases.index") }}
    </div>
  </div>
{% endblock %}