postfix_mail_admin/views/aliases.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required
from flask_sqlalchemy import Pagination

from ..forms import AliasForm
from ..services import db
from ..models import Alias

aliases_blueprint = Blueprint("aliases", __name__)


@aliases_blueprint.route("/", endpoint="index")
@login_required
def index():
    pager: Pagination = Alias.query.paginate(per_page=25, max_per_page=50)
    return render_template("aliases/index.html", pager=pager)


@aliases_blueprint.route("/create", endpoint="create", methods=["GET", "POST"])
@login_required
def create():
    form = AliasForm()

    if form.validate_on_submit():
        alias = Alias()
        form.populate_obj(alias)

        db.session.add(alias)
        db.session.commit()

        flash(f"Alias {alias} has been successfully created", "success")
        return redirect(url_for(".index"))

    return render_template("aliases/create.html", form=form)


@aliases_blueprint.route(
    "/<int:alias_id>/edit", endpoint="edit", methods=["GET", "POST"]
)
@login_required
def edit(alias_id):
    alias = Alias.query.get_or_404(alias_id)
    form = AliasForm(obj=alias)

    if form.validate_on_submit():
        form.populate_obj(alias)

        db.session.add(alias)
        db.session.commit()

        flash(f"Alias {alias} has been successfully updated", "success")
        return redirect(url_for(".index"))

    return render_template("aliases/edit.html", alias=alias, form=form)


@aliases_blueprint.route("/<int:alias_id>/delete", endpoint="delete")
@login_required
def remove(alias_id):
    alias = Alias.query.get_or_404(alias_id)

    db.session.delete(alias)
    db.session.commit()

    flash(f"Alias {alias} has been successfully deleted", "success")
    return redirect(url_for(".index"))

postfix_mail_admin/views/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, logout_user, login_user
from passlib.hash import bcrypt

from ..forms import LoginForm
from ..models import User

auth_blueprint = Blueprint("auth", __name__)


@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if (
            user is not None
            and user.is_active
            and bcrypt.verify(form.password.data, user.password)
        ):
            login_user(user)
            return redirect(url_for("dashboard.index"))

        flash("Wrong email or password", "warning")

    return render_template("login.html", form=form)


@auth_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

postfix_mail_admin/views/domains.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required

from ..forms import DomainForm
from ..services import db
from ..models import Domain

domains_blueprint = Blueprint("domains", __name__)


@domains_blueprint.route("/", endpoint="index")
@login_required
def index():
    domains = Domain.query.all()
    return render_template("domains/index.html", domains=domains)


@domains_blueprint.route("/create", endpoint="create", methods=["GET", "POST"])
@login_required
def create():
    form = DomainForm()

    if form.validate_on_submit():
        domain = Domain()
        form.populate_obj(domain)

        db.session.add(domain)
        db.session.commit()

        flash(f"Domain {domain.fqdn} has been successfully created", "success")
        return redirect(url_for(".index"))

    return render_template("domains/create.html", form=form)


@domains_blueprint.route(
    "/<int:domain_id>/edit", endpoint="edit", methods=["GET", "POST"]
)
@login_required
def edit(domain_id):
    domain: Domain = Domain.query.get_or_404(domain_id)
    form = DomainForm(obj=domain)

    if form.validate_on_submit():
        form.populate_obj(domain)

        db.session.add(domain)
        db.session.commit()

        flash(f"Domain {domain.fqdn} has been successfully updated", "success")
        return redirect(url_for(".index"))

    return render_template("domains/edit.html", domain=domain, form=form)


@domains_blueprint.route("/<int:domain_id>/delete", endpoint="delete")
@login_required
def remove(domain_id):
    domain = Domain.query.get_or_404(domain_id)
    db.session.delete(domain)
    db.session.commit()

    flash(f"Domain {domain.fqdn} has been successfully deleted", "success")
    return redirect(url_for(".index"))

postfix_mail_admin/views/users.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user

from ..forms import UserUpdateForm
from ..services import db

users_blueprint = Blueprint("users", __name__)


@users_blueprint.route("/me", endpoint="profile")
@login_required
def profile():
    return render_template("users/profile.html", user=current_user)


@users_blueprint.route("/me/edit", endpoint="edit", methods=["GET", "POST"])
@login_required
def edit():
    user = current_user
    form = UserUpdateForm(obj=user)

    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()

        flash("User has been successfully updated", "success")
        return redirect(url_for(".profile"))

    return render_template("users/edit.html", user=user, form=form)

postfix_mail_admin/templates/partials/footer.html
<footer class="footer container">
  <p class="text-muted">&copy; 2020, Sergey Dyachok</p>
</footer>

postfix_mail_admin/templates/partials/header.html
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container">
      <a href="{{ url_for("dashboard.index") }}"
         class="navbar-brand text-uppercase"
      >Postfix Mail</a>
      <button class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if current_user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href="{{ url_for("dashboard.index") }}" class="nav-link">Dashboard</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for("domains.index") }}" class="nav-link">Domains</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for("mailboxes.index") }}" class="nav-link">Mailboxes</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for("aliases.index") }}" class="nav-link">Aliases</a>
            </li>

            <li class="nav-item dropdown">
              <a href="#"
                 class="nav-link dropdown-toggle"
                 id="navbarDropdown"
                 role="button"
                 data-toggle="dropdown"
                 aria-haspopup="true"
                 aria-expanded="false"
              >Account</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a href="{{ url_for("users.profile") }}" class="dropdown-item">Profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for("auth.logout") }}">Logout</a>
              </div>
            </li>
          </ul>
        {% else %}
          <div class="ml-auto">
            <a href="{{ url_for("auth.login") }}" class="btn btn-raised btn-dark">Login</a>
          </div>
        {% endif %}
      </div>
    </div>
  </nav>
</header>

postfix_mail_admin/templates/partials/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible fade show">
        <strong>{{ category.title() }}!</strong> {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}