postfix_mail_admin/models/mailbox.py
from passlib.hash import bcrypt

from .base import BaseModel
from ..services import db


class Mailbox(BaseModel):
    """A domain-related mailbox"""

    __tablename__ = "mailboxes"
    __table_args__ = (
        db.UniqueConstraint("domain_id", "name", name="ix_mailboxes_email"),
    )

    domain_id = db.Column(
        db.Integer,
        db.ForeignKey("domains.id", ondelete="CASCADE", onupdate="CASCADE"),
        nullable=False,
        index=True,
        info={"label": "Domain"},
    )
    name = db.Column(db.String(150), nullable=False, info={"label": "Mailbox"})
    password = db.Column(
        db.String(150), nullable=False, info={"label": "Password"},
    )

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"<Mailbox {self.name}>"

    def __hash__(self):
        return hash((self.id, self.name, self.domain_id))

    @property
    def email(self):
        return f"{self.name}@{self.domain.fqdn}" if self.domain_id else "<none>"

    def set_password(self, value):
        self.password = bcrypt.hash(value)

postfix_mail_admin/views/mailboxes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required
from flask_sqlalchemy import Pagination

from ..forms import MailboxForm, MailboxUpdateForm
from ..services import db
from ..models import Mailbox

mailboxes_blueprint = Blueprint("mailboxes", __name__)


@mailboxes_blueprint.route("/", endpoint="index")
@login_required
def index():
    pager: Pagination = Mailbox.query.paginate(per_page=25, max_per_page=50)
    return render_template("mailboxes/index.html", pager=pager)


@mailboxes_blueprint.route(
    "/create", endpoint="create", methods=["GET", "POST"]
)
@login_required
def create():
    form = MailboxForm()

    if form.validate_on_submit():
        mailbox = Mailbox()
        form.populate_obj(mailbox)
        mailbox.set_password(form.data["password"])

        db.session.add(mailbox)
        db.session.commit()

        flash(
            f"Mailbox {mailbox.email} has been successfully created", "success"
        )
        return redirect(url_for(".index"))

    return render_template("mailboxes/create.html", form=form)


@mailboxes_blueprint.route(
    "/<int:mailbox_id>/edit", endpoint="edit", methods=["GET", "POST"]
)
@login_required
def edit(mailbox_id):
    mailbox = Mailbox.query.get_or_404(mailbox_id)
    form = MailboxUpdateForm(obj=mailbox)

    if form.validate_on_submit():
        mailbox.name = form.data["name"]
        mailbox.domain = form.data["domain"]
        mailbox.is_active = form.data["is_active"]
        if len(form.data["password"]) > 0:
            mailbox.set_password(form.data["password"])

        db.session.add(mailbox)
        db.session.commit()

        flash(
            f"Mailbox {mailbox.email} has been successfully updated", "success"
        )
        return redirect(url_for(".index"))

    return render_template("mailboxes/edit.html", mailbox=mailbox, form=form)


@mailboxes_blueprint.route("/<int:mailbox_id>/delete", endpoint="delete")
@login_required
def remove(mailbox_id):
    mailbox = Mailbox.query.get_or_404(mailbox_id)
    mailbox_name = mailbox.email

    db.session.delete(mailbox)
    db.session.commit()

    flash(f"Mailbox {mailbox_name} has been successfully deleted", "success")
    return redirect(url_for(".index"))

postfix_mail_admin/templates/mailboxes/_form.html
{{ form.hidden_tag() }}

<div class="mt-4 form-row">
  <div class="col">
    <div class="form-group">
      {{ form.name.label(class_="bmd-label-static") }}
      {{ form.name(class_="form-control is-invalid" if form.name.errors else "form-control", autocomplete="username") }}
      {% if form.name.errors %}
        <div class="invalid-feedback">
          {% for error in form.name.errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </div>
  <div class="col">
    <div class="form-group">
      {{ form.domain.label(class_="bmd-label-static") }}
      <div class="input-group align-items-center">
        <div class="input-group-prepend mr-1">
          <span>&commat;</span>
        </div>
        {{ form.domain(class_="form-control is-invalid" if form.domain.errors else "form-control", size=1) }}
        {% if form.domain.errors %}
          <div class="invalid-feedback">
            {% for error in form.domain.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<div class="form-group">
  {{ form.password.label(class_="bmd-label-static") }}
  {{ form.password(class_="form-control is-invalid" if form.password.errors else "form-control", autocomplete="new-password") }}
  {% if form.password.errors %}
    <div class="invalid-feedback">
      {% for error in form.password.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
  {% endif %}
</div>

<div class="mt-4 checkbox">
  <label for="{{ form.is_active.label.field_id }}">
    {{ form.is_active }}
    {{ form.is_active.label.text }}
  </label>
</div>

postfix_mail_admin/templates/mailboxes/create.html
{% extends "base.html" %}

{% block title %}New mailbox{% endblock %}

{% block content %}
  <div class="mt-6 row justify-content-center">
    <div class="col-sm-12 col-md-8">
      <h1>Add a new mailbox</h1>

      <div class="mt-4">
        <form action="{{ url_for("mailboxes.create") }}" method="post">
          {% include "mailboxes/_form.html" %}

          <div class="mt-4 btn-group">
            <button type="submit" class="btn btn-raised btn-primary">Create</button>
            <a href="{{ url_for("mailboxes.index") }}" class="ml-2 btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

postfix_mail_admin/templates/mailboxes/edit.html
{% extends "base.html" %}

{% block title %}Edit {{ mailbox.email }}{% endblock %}

{% block content %}
  <div class="mt-6 row justify-content-center">
    <div class="col-sm-12 col-md-6">
      <h1>Edit {{ mailbox.email }}</h1>

      <div class="mt-4">
        <form action="{{ url_for("mailboxes.edit", mailbox_id=mailbox.id) }}" method="post">
          {% include "mailboxes/_form.html" %}

          <div class="mt-4 btn-group">
            <button type="submit" class="btn btn-raised btn-primary">Save</button>
            <a href="{{ url_for("mailboxes.index") }}" class="ml-2 btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

postfix_mail_admin/templates/mailboxes/index.html
{% extends "base.html" %}

{% block title %}Mailboxes{% endblock %}

{% block content %}
  <div class="mt-4">
    <div class="d-flex">
      <h1>Mailboxes</h1>
      <div class="ml-auto">
        <a href="{{ url_for("mailboxes.create") }}"
           class="btn btn-raised btn-primary d-inline-flex align-items-center"
           title="Add a new mailbox">
          <i class="material-icons">add</i>
          <span class="pl-1">Add</span>
        </a>
      </div>
    </div>

    <div class="mt-4 table-responsive-md">
      <table class="table table-sm">
        <thead>
        <tr>
          <th>ID</th>
          <th>Mailbox</th>
          <th>Domain</th>
          <th>Is active?</th>
          <th>Created At</th>
          <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        {% for mailbox in pager.items %}
          <tr>
            <th scope="row" class="align-middle">{{ mailbox.id }}</th>
            <td class="align-middle">{{ mailbox.name }}</td>
            <td class="align-middle">{{ mailbox.domain.fqdn }}</td>
            <td class="align-middle">
              {% if mailbox.is_active %}
                <span class="text-success">
                    <i class="material-icons font-weight-bold">check</i>
                  </span>
              {% else %}
                <span class="text-warning">
                    <i class="material-icons font-weight-bold">remove</i>
                  </span>
              {% endif %}
            </td>
            <td class="align-middle">{{ mailbox.created_at.strftime("%c") }}</td>
            <td class="align-middle">
              <div class="btn-toolbar btn-group-sm" role="toolbar" aria-label="Actions">
                <a href="{{ url_for("mailboxes.edit", mailbox_id=mailbox.id) }}"
                   class="btn btn-info" title="Edit">
                  <i class="material-icons">edit</i>
                </a>
                <a href="{{ url_for("mailboxes.delete", mailbox_id=mailbox.id) }}"
                   class="btn btn-danger" title="Delete"
                   onclick="return confirm('Are you sure you want to delete {{ mailbox.email }}?')"
                >
                  <i class="material-icons">delete</i>
                </a>
              </div>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

      <!-- Pagination -->
      {% from "helpers/_pagination.html" import render_pagination %}
      {{ render_pagination(pager, "mailboxes.index") }}
    </div>
  </div>
{% endblock %}